name: 'OpenAI Action'
description: 'TBD'

inputs:
  github_token:
    description: 'GitHub token for authentication.'
    required: true
  openai_api_key:
    description: 'OpenAI API key for accessing OpenAI services.'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare Data and Generate AI Completion in Docker
      uses: docker://registry.gitlab.com/gitlab-ci-utils/curl-jq
      with:
        # Remove or replace the default entrypoint
        entrypoint: /bin/sh
        # Pass commands as a single string to `sh -c`
        args: |- 
          -c "
          curl -V
          "

    # - name: Update Issue Using GitHub Script
    #   uses: actions/github-script@v7
    #   with:
    #     github-token: ${{ inputs.github_token }}
    #     script: |
    #       const fs = require('fs');
    #       const issueNumber = parseInt(fs.readFileSync('issue_number.txt', 'utf8').trim(), 10);
    #       const refined = fs.readFileSync('issue_description.txt', 'utf8');

    #       await github.rest.issues.update({
    #         owner: context.repo.owner,
    #         repo: context.repo.repo,
    #         issue_number: issueNumber,
    #         body: refined
    #       });
