name: 'OpenAI Action'
description: 'TBD'

inputs:
  github_token:
    description: 'GitHub token for authentication.'
    required: true
  openai_api_key:
    description: 'OpenAI API key for accessing OpenAI services.'
    required: true

runs:
  using: 'composite'
  steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Prepare Data and Generate AI Completion in Docker
      if: ${{ github.event_name == 'pull_request' }}
      uses: docker://registry.gitlab.com/gitlab-ci-utils/curl-jq
      with:
        entrypoint: /bin/sh
        args: |-
          -c '
            pull_request_event_trimmed=$(jq "{ pull_request: { title: .pull_request.title, body: .pull_request.body, number: .pull_request.number } }" "$GITHUB_EVENT_PATH" | head -c 3000)
            echo "$pull_request_event_trimmed" > pr_event_trimmed.json

            pull_number=$(echo "$pull_request_event_trimmed" | jq -r ".pull_request.number")
            echo "$pull_number" > pull_number.txt

            system_message="You are a helpful AI. Create an improved pull request description."
            user_prompt="Event:\n$(cat pr_event_trimmed.json)\nPlease create an improved PR description."

            data=$(jq -n \
              --arg system "$system_message" \
              --arg user "$user_prompt" \
              "{
                \"model\": \"gpt-4\",
                \"messages\": [
                  {
                    \"role\": \"system\",
                    \"content\": \$system
                  },
                  {
                    \"role\": \"user\",
                    \"content\": \$user
                  }
                ]
              }"
            )

            response=$(curl -s -X POST "https://api.openai.com/v1/chat/completions" \
              -H "Content-Type: application/json" \
              -H "Authorization: Bearer ${{ inputs.openai_api_key }}" \
              -d "$data")

            body=$(echo "$response" | jq -r ".choices[0].message.content")
            echo "$body" > body.txt
          '

    - name: Update PR Using GitHub Script
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const pullNumber = parseInt(require('fs').readFileSync('pull_number.txt', 'utf8').trim(), 10);
          const body = require('fs').readFileSync('body.txt', 'utf8');
          await github.rest.pulls.update({
            owner: context.repo.owner,
            repo: context.repo.repo,
            pull_number: pullNumber,
            body: body
          });
