name: 'On Pull Request Opened'
description: 'Triggers on opening a pull request and performs specific actions.'

inputs:
  github_token:
    description: 'GitHub token for authentication.'
    required: true
  openai_api_key:
    description: 'OpenAI API key for accessing OpenAI services.'
    required: true
  pull_request_template:
    description: 'Path to the pull request template file.'
    required: true
    default: '.github/pull_request_template.md'

runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate AI Completion
      shell: bash
      run: |
        pull_request_event_trimmed=$(jq '{ pull_request: { title: .pull_request.title, body: .pull_request.body, number: .pull_request.number } }' "$GITHUB_EVENT_PATH" | head -c 3000)
        pull_request_template_trimmed=$(head -c 3000 "${{ inputs.pull_request_template }}")
        request_data=$(jq -n \
          --arg system "You are a helpful AI. Create an improved pull request description." \
          --arg user "Event:\n$pull_request_event_trimmed\n\nTemplate:\n$pull_request_template_trimmed\n\nPlease create an improved PR description." \
          '{
            "model": "gpt-4",
            "messages": [
              {
                "role": "system",
                "content": $system
              },
              {
                "role": "user",
                "content": $user
              }
            ]
          }'
        )

        curl -X POST "https://api.openai.com/v1/chat/completions" \
          -H "Content-Type: application/json" \
          -H "Authorization: Bearer ${{ inputs.openai_api_key }}" \
          -d "$request_data"
