name: 'On Pull Request Opened'
description: 'TBD'
inputs:
  github_token:
    description: 'TBD'
    required: true
  openai_api_key:
    description: 'TBD'
    required: true
  pull_request_template:
    description: 'TBD'
    required: true
    default: '.github/pull_request_template.md'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl
      shell: bash
    - name: Checkout code
      uses: actions/checkout@v3
