name: Example Workflow 2

on: [pull_request]

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Generate Code
        uses: ./actions/generate-code
