name: On Issues Opened
on:
  issues:
    types: [opened]
jobs:
  handle_issues_opened:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: On Issues Opened
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
