name: On Pull Request Opened
on:
  pull_request:
    types: [opened]

jobs:
  refine_and_update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3    

      - name: On Pull Request Opened
        uses: ./on_pull_request_opened
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
