name: On Pull Request Opened
on:
  pull_request:
    types: [opened]
jobs:
  handle_pull_request_opened:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3    
      - name: On Pull Request Opened
        uses: ./
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
